image: docker

services:
    - docker:dind

stages:
    - test
    - prod

pushing-to-master:
    stage: prod
    only:
        - master
    script:
        - sudo apt-get install -y python-pip
        - sudo pip install docker-compose
        - docker-compose up -d --build
        - python tcm.py banana
        - python tcm.py is-prime 26
        - python tcm.py md5 a test string
        - python tcm.py fibonacci 99
        - python tcm.py factorial 7
        - python tcm.py slack-alert This is an automated test
    environment: master
