image: docker

services:
    - docker:dind

stages:
    - test
    - prod

pushing-to-master:
    stage: prod
    only:
        - master
    script:
        # - apt-get install -y python-pip
        # - pip install docker-compose
        - docker-compose up -d --build
        - python tcm.py banana
        - echo "script for testing all endpoints here"
    environment: master
