version: "3"
services:

  heavy:
    build: ./heavy
    ports:
      - 5001:5000

  light:
    build: ./light
    ports:
      - 5002:5000
    depends_on:
      - heavy

  tcm:
    build: ./tcm
    ports:
      - 5003:5000
    depends_on:
      - heavy
